In [1]:
import os
import os.path as osp

import torch
import numpy as np 

from mylib import labelme_utils as lu 
from mylib import polSAR_utils as psr

In [2]:
path = r'data/PolSAR_building_det/data/GF3/mainama/20180627/HAalpha'
a = np.load(osp.join(path, 'unnormed.npy'))

In [3]:
num_nan = np.isnan(a).sum()
num_inf = np.isinf(a).sum()
num_nan, num_inf

(0, 0)

In [7]:
path = r'/data/csl/PolSAR_building_det/zscored/GF3'
model_path = osp.split(osp.split(path)[0])[0]
osp.join(model_path, f'PCA_{3}')

'/data/csl/PolSAR_building_det/PCA_3'

In [2]:
a = np.arange(4)
b = None
a+b

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [20]:
x = np.array([[1,2],[3,4]])
b = np.repeat(x, 4, axis=0)
c = np.tile(x, (3, 1))
x, b, c

(array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]]),
 array([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]]))

In [21]:
x[1,1]=10
x, b, c

(array([[ 1,  2],
        [ 3, 10]]),
 array([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [3, 4]]),
 array([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]]))

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.tile(a, )

In [18]:
c3 = psr.read_c3('/data/csl/SAR_CD/GF3/data/E132_N34_日本安芸/降轨/2/20170531/C3', out='complex_vector_6')
c3 = np.abs(c3)
c3[c3>100] = 100
# c3[c3<np.finfo]=np.finfo
# c3 = np.log(c3)
np.histogram(c3)

(array([ 3893179,  3777938,  3528564,  2970715,  2690573,  2421288,
         2182400,  1752256,  1807065, 82782270]),
 array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       dtype=float32))

In [3]:
img_shape = [6946, 4096]
slice_idx = 92
patch_shape = [512, 512]
lu.get_corrds_from_slice_idx(img_shape=img_shape, patch_shape=patch_shape, slice_idx=slice_idx)

array([5632, 2048], dtype=int32)

In [19]:
a=np.load(r'data/SAR_CD/GF3/data/E132_N34_日本安芸/升轨/2/20170723/C3/complex_vector_6_mean.npy')
a

array([[[ 6.9514550e-02+0.0000000e+00j]],

       [[-7.6923570e-06+1.7181954e-04j]],

       [[ 2.4461713e-02-5.2470178e-03j]],

       [[ 1.7439649e-02+0.0000000e+00j]],

       [[-6.4297354e-05-5.8014892e-05j]],

       [[ 6.3866749e-02+0.0000000e+00j]]], dtype=complex64)