In [3]:
import numpy as np 
from mylib import labelme_utils as lu 
from mylib import polSAR_utils as psr


In [18]:
c3 = psr.read_c3('/data/csl/SAR_CD/GF3/data/E132_N34_日本安芸/降轨/2/20170531/C3', out='complex_vector_6')
c3 = np.abs(c3)
c3[c3>100] = 100
# c3[c3<np.finfo]=np.finfo
# c3 = np.log(c3)
np.histogram(c3)

(array([ 3893179,  3777938,  3528564,  2970715,  2690573,  2421288,
         2182400,  1752256,  1807065, 82782270]),
 array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.],
       dtype=float32))

In [3]:
img_shape = [6946, 4096]
slice_idx = 92
patch_shape = [512, 512]
lu.get_corrds_from_slice_idx(img_shape=img_shape, patch_shape=patch_shape, slice_idx=slice_idx)

array([5632, 2048], dtype=int32)

In [19]:
a=np.load(r'data/SAR_CD/GF3/data/E132_N34_日本安芸/升轨/2/20170723/C3/complex_vector_6_mean.npy')
a

array([[[ 6.9514550e-02+0.0000000e+00j]],

       [[-7.6923570e-06+1.7181954e-04j]],

       [[ 2.4461713e-02-5.2470178e-03j]],

       [[ 1.7439649e-02+0.0000000e+00j]],

       [[-6.4297354e-05-5.8014892e-05j]],

       [[ 6.3866749e-02+0.0000000e+00j]]], dtype=complex64)